[package]
name = "glacio-http"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
glacio = { path = "../glacio" }
iron = "0.5"
logger = "0.3"
params = "0.6"
persistent = "0.3"
router = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
