[package]
name = "glacio"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
docopt = "*"
env_logger = "*"
iron = "*"
log = "*"
persistent = "*"
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
toml = "*"

[[bin]]
name = "glacio-api"
doc = false
