[package]
name = "glacio"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
chrono = "*"
docopt = "*"
lazy_static = "*"
regex = "*"
sbd = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
toml = "*"
url = "*"
