[package]
name = "glacio"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "0.2"
regex = "0.2"
sbd = "0.1"
serde = "1.0"
serde_derive = "1.0"
url = "1.5"
