[package]
name = "sutron"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
byteorder = "1.2"
chrono = "0.4"
clap = { version = "2.32", features = ["yaml"] }
failure = "0.1"
regex = "1.0"
sbd = "0.2"
