image_document_root = "/home/iridiumcam/StarDot"
image_server = "http://iridiumcam.lidar.io"
iridium_sbd_root = "/var/iridium"

[[atlas]]
id = "south"
name = "ATLAS South"

[[atlas]]
id = "north"
name = "ATLAS North"

[[cameras]]
id = "ATLAS_CAM"
name = "ATLAS South site"
paths = ["/home/iridiumcam/StarDot/ATLAS_CAM"]
description = "A wide-angle view of the ATLAS South system."

[[cameras]]
id = "ATLAS_CAM2"
name = "ATLAS South scanner"
paths = ["/home/iridiumcam/StarDot/ATLAS_CAM2"]
description = "A close-up view of the ATLAS South scanner."

[[cameras]]
id = "HEL_BERGCAM3"
name = "ATLAS North site"
paths = ["/home/iridiumcam/StarDot/HEL_BERGCAM3/StarDot1", "/home/iridiumcam/StarDot/HEL_BERGCAM3/StarDot2"]
description = "A dual-camera wide-angle view of the ATLAS North system."

[[cameras]]
id = "HEL_ATLASNORTH"
name = "ATLAS North scanner"
paths = ["/home/iridiumcam/StarDot/HEL_ATLASNORTH"]
description = "A close-up view of the ATLAS North scanner."

[[cameras]]
id = "HEL_DUAL"
name = "Helheim Glacier"
paths = ["/home/iridiumcam/StarDot/HEL_DUAL/StarDot1", "/home/iridiumcam/StarDot/HEL_DUAL/StarDot2"]
description = "A dual-camera view of the Helheim Glacier."

[[cameras]]
id = "HEL_BERGCAM2"
name = "Sermerlik Fjord north"
paths = ["/home/iridiumcam/StarDot/HEL_BERGCAM2/StarDot1", "/home/iridiumcam/StarDot/HEL_BERGCAM2/StarDot2"]
description = "A north-looking dual-camera view of icebergs in the Sermerlik Fjord."

[[cameras]]
id = "HEL_BERGCAM1"
name = "Sermerlik Fjord south"
paths = ["/home/iridiumcam/StarDot/HEL_BERGCAM1/StarDot1", "/home/iridiumcam/StarDot/HEL_BERGCAM1/StarDot2"]
description = "A south-looking dual-camera view of icebergs in the Sermerlik Fjord."
