image_document_root = "/Users/rdcrlpjg/iridiumcam/StarDot"
image_server = "http://localhost:8000"
iridium_sbd_root = "/Users/rdcrlpjg/iridium"

[[sites]]
id = "south"
name = "ATLAS South"

[[sites]]
id = "north"
name = "ATLAS North"

[[cameras]]
id = "ATLAS_CAM"
name = "ATLAS South site"
path = "/Users/rdcrlpjg/iridiumcam/StarDot/ATLAS_CAM"
description = "A wide-angle view of the ATLAS South system."

[[cameras]]
id = "ATLAS_CAM2"
name = "ATLAS South scanner"
path = "/Users/rdcrlpjg/iridiumcam/StarDot/ATLAS_CAM2"
description = "A close-up view of the ATLAS South scanner."

[[cameras]]
id = "HEL_BERGCAM3"
dual = true
name = "ATLAS North site"
paths = ["/Users/rdcrlpjg/iridiumcam/StarDot/HEL_BERGCAM3/StarDot1", "/Users/rdcrlpjg/iridiumcam/StarDot/HEL_BERGCAM3/StarDot2"]
description = "A dual-camera wide-angle view of the ATLAS North system."

[[cameras]]
id = "HEL_ATLASNORTH"
name = "ATLAS North scanner"
path = "/Users/rdcrlpjg/iridiumcam/StarDot/HEL_ATLASNORTH"
description = "A close-up view of the ATLAS North scanner."

[[cameras]]
id = "HEL_DUAL"
dual = true
name = "Helheim Glacier dual"
paths = ["/Users/rdcrlpjg/iridiumcam/StarDot/HEL_DUAL/StarDot1", "/Users/rdcrlpjg/iridiumcam/StarDot/HEL_DUAL/StarDot2"]
description = "A dual-camera view of the Helheim Glacier."

[[cameras]]
id = "HEL_BERGCAM1"
dual = true
name = "Sermerlik Fjord dual (south)"
paths = ["/Users/rdcrlpjg/iridiumcam/StarDot/HEL_BERGCAM1/StarDot1", "/Users/rdcrlpjg/iridiumcam/StarDot/HEL_BERGCAM1/StarDot2"]
description = "A dual-camera southerly view of icebergs in the Sermerlik Fjord."


[[cameras]]
id = "HEL_BERGCAM2"
dual = true
name = "Sermerlik Fjord dual (north)"
paths = ["/Users/rdcrlpjg/iridiumcam/StarDot/HEL_BERGCAM2/StarDot1", "/Users/rdcrlpjg/iridiumcam/StarDot/HEL_BERGCAM2/StarDot2"]
description = "A dual-camera northerly view of icebergs in the Sermerlik Fjord."
